export const agentJourney = [
  { title: 'Answer a question', short: 'Chat', added: 'A language model turns your request into a response.', example: '“Help me plan our website launch.” You get a suggested checklist.', limit: 'It has not read your project files or done any of the work.', control: 'You supply the request, judge the answer, and take the next step.', flow: ['Your question', 'Model', 'Suggested plan'], next: 'A useful plan needs the details of your actual project.' },
  { title: 'Read relevant information', short: 'Context', added: 'Supply the project brief and meeting notes, directly or through retrieval: software finding relevant passages.', example: '“Use our brief to identify what is still missing before launch.” The answer can point to the supplied evidence.', limit: 'Missing or outdated documents can still produce an incomplete answer. Retrieved text does not retrain the model.', control: 'You choose which sources it can access and check that its claims follow from them.', flow: ['Question + documents', 'Model', 'Grounded answer'], next: 'A repeatable task may need several steps in a predictable order.' },
  { title: 'Follow a workflow', short: 'Workflow', added: 'Code connects model calls and checks in a sequence you design.', example: 'Extract tasks from the notes, draft a launch checklist, then check that every task has an owner.', limit: 'The model fills in steps; code decides the order and handles failures. A timer can start this workflow without making it an agent.', control: 'You define the steps, checks, retry limits, and approval points.', flow: ['Extract tasks', 'Draft checklist', 'Check required fields'], next: 'Sometimes the model needs to choose an action, not just write text.' },
  { title: 'Use tools', short: 'Tools', added: 'The model can request a named action. Software checks permission, runs it, and returns the result.', example: 'It requests the current launch date from your tracker, then uses the returned date in its answer.', limit: 'Requesting an action is different from executing it. A proposed tracker update is not an approved change.', control: 'You decide which tools exist, what they may access, and which actions need approval.', flow: ['Model requests action', 'Code checks + runs tool', 'Result returns to model'], next: 'One action may reveal a new problem that needs another action.' },
  { title: 'Work toward an outcome', short: 'Agent', added: 'A loop lets the model inspect results and choose what to do next. The surrounding software runs tools and enforces limits.', example: '“Find what is blocking launch.” It reads the checklist, investigates missing approvals, and follows up on the evidence it finds.', limit: 'It can repeat mistakes, take unhelpful detours, or stop too early. More steps are not proof of progress.', control: 'You set the goal, permissions, budget, and stopping conditions, then review the result.', flow: ['Choose next step', 'Act through tools', 'Inspect result'], next: 'Some jobs benefit from separate specialists or an independent review.' },
  { title: 'Divide the work', short: 'Team · optional', added: 'Several agents work with separate roles and contexts, passing findings between them.', example: 'A lead asks one agent to inspect the launch requirements and another to review the proposed plan, then reconciles their findings.', limit: 'Agents can duplicate work or share the same blind spots. A team adds coordination and cost; a single agent may be enough.', control: 'You decide the roles, shared information, and who resolves disagreements.', flow: ['Lead assigns work', 'Researcher + reviewer', 'Lead combines findings'], next: 'Whether there is one agent or a team, ongoing work needs a way to resume later.' },
  { title: 'Keep working over time', short: 'Always-on', added: 'Saved records, schedules or events, and a continuing runtime let an agent start or resume work after you leave.', example: 'Each morning, it loads the project record, checks for changes, investigates new blockers, and brings exceptions to you. It saves an update for the next session.', limit: 'Always-on does not mean continuously thinking. Software wakes the agent, supplies context, and saves progress. Stale records and repeated triggers still need handling.', control: 'You set the triggers and approval rules, inspect the record of actions, and can pause or stop the system.', flow: ['Schedule or event', 'Load record + run agent', 'Save progress + wait'], next: 'Stop adding capabilities when the simplest design meets your task.' },
];
