export interface ArchitectureNode { title: string; detail: string; x: number; y: number; kind?: 'model' | 'control' | 'end' }
export interface ArchitectureEdge { from: number; to: number; label: string; kind?: 'data' | 'return'; route?: 'outside' }
export interface Architecture { title: string; subtitle: string; nodes: ArchitectureNode[]; edges: ArchitectureEdge[]; distinction: string; checks: [string, string][] }
const n = (title:string, detail:string, col:number, row:number, kind?:ArchitectureNode['kind']):ArchitectureNode => ({title,detail,x:20+337*col,y:28+170*row,kind});
const e = (from:number,to:number,label:string,kind?:ArchitectureEdge['kind'],route?:'outside'):ArchitectureEdge => ({from,to,label,kind,route});
const agent:Architecture = {
  title:'A decision loop, with a way out.', subtitle:'The model chooses a proposed next step. Software decides whether it can run.',
  nodes:[n('Goal + context','Task, instructions, selected history',0,0),n('Model decision','Request a tool or return an answer',1,0,'model'),n('Execution gate','Arguments, permissions, budgets',2,0,'control'),n('Run allowed tool','Bounded operation in the environment',2,1),n('Observe the result','Return output or a useful error',1,1),n('Finish or hand back','Return work, evidence, and gaps',0,1,'end'),n('Pause or refuse','Approval needed, denied, or capped',2,2,'end')],
  edges:[e(0,1,'context','data'),e(1,2,'tool request'),e(2,3,'allowed'),e(3,4,'observation','data'),e(4,1,'next decision','return'),e(1,5,'final answer'),e(2,6,'cannot proceed',undefined,'outside')],
  distinction:'Reasoning helps the model choose useful actions. The loop supplies feedback; the harness supplies execution, state, and enforced limits. None of those makes the answer automatically correct.',
  checks:[['Control','Tool output is evidence, not permission to take another action.'],['Stopping','Finish, ask for help, or stop at a step, time, or cost limit.'],['Verification','Inspect the environment and the final artifact, not just the model’s account of its work.']]
};
export const architectures:Record<string,Architecture> = {
  'single-agent':agent,
  'agent-harness':{...agent,title:'The harness makes the loop executable.',subtitle:'Every model request passes through application controls before it affects the world.'},
  'agentic-rag':{...agent,title:'Search again only when the evidence calls for it.',subtitle:'An agent chooses searches and document reads; the application enforces access and a search budget.',nodes:agent.nodes.map((node,i)=>i===0?{...node,title:'Research question',detail:'Scope, permitted sources, constraints'}:i===3?{...node,title:'Search or read',detail:'Retrieve passages or open a source'}:i===4?{...node,title:'Inspect evidence',detail:'Coverage, conflicts, source provenance'}:i===5?{...node,title:'Answer or report gaps',detail:'Citations, uncertainty, unresolved facts'}:node),distinction:'More searches create opportunities to fill gaps and to introduce errors. Judge evidence coverage and claim support separately from how many steps the agent took.'},
  rag:{title:'Two paths meet at retrieval.',subtitle:'Indexing prepares the sources. A query selects evidence for this answer.',nodes:[n('Source documents','Versioned text with access rules',0,0),n('Prepare the index','Split, preserve IDs, index the content',1,0),n('Question','What the user needs to know',0,1),n('Retrieve + select','Lexical, vector, hybrid; optional rerank',1,1),n('Generate an answer','Question + selected evidence',2,1,'model'),n('Check or abstain','Supported claims and valid citations',2,2,'end')],edges:[e(0,1,'indexing','data'),e(1,3,'searchable sources','data'),e(2,3,'query','data'),e(3,4,'evidence packet','data'),e(4,5,'draft')],distinction:'RAG is retrieval-augmented generation, not a guarantee of truth. A missing answer may be a retrieval failure, a source gap, or a generation error; those need different fixes.',checks:[['Before retrieval','Apply document permissions. Keep source IDs and revision metadata.'],['Before answering','Check whether the selected evidence covers every part of the question.'],['After answering','A real citation ID can still support the wrong claim. Check entailment as well as existence.']]},
  'knowledge-graphs':{title:'Relationships are data you can query.',subtitle:'These arrows name relationships between entities. They are not execution steps.',nodes:[n('DW-480','Appliance model',0,0),n('P-17','Replacement part',1,0),n('Repair Depot','Service company',2,0),n('Standard warranty','Coverage policy',0,1),n('Motor assembly','Part category',1,1),n('Service record 82','Dated repair evidence',2,1)],edges:[e(1,0,'fits','data'),e(1,4,'is a','data'),e(0,3,'covered by','data'),e(2,5,'performed','data'),e(5,0,'serviced','data','outside')],distinction:'A graph can make a multi-hop relationship explicit. It cannot make an incorrect or outdated edge true. Keep evidence, timestamps, and entity identity alongside relationships.',checks:[['Query','Which authorized company serviced a model that uses part P-17?'],['Trace','P-17 → fits → DW-480 ← serviced ← record 82 ← performed ← Repair Depot.'],['Boundary','The graph stores an authorization claim about Repair Depot only if you have a separate sourced fact for it. A service record alone does not establish authorization.']]},
  'agent-teammates':{title:'Always available does not mean always generating.',subtitle:'A durable trigger starts a bounded run. The system waits between runs.',nodes:[n('Schedule or event','A timer fires or new work arrives',0,0),n('Claim the event','Dedupe; load durable state',1,0,'control'),n('Bounded agent run','Reason, use tools, check progress',2,0,'model'),n('Wait for next event','No model call while idle',0,1,'end'),n('Persist the result','Checkpoint + intended effects',1,1),n('Review or dispatch','Authorized action or human handoff',2,1,'control')],edges:[e(0,1,'event'),e(1,2,'new work'),e(2,5,'proposed effect'),e(5,4,'record outcome','data'),e(4,3,'run complete'),e(3,0,'next trigger','return')],distinction:'Persistence, triggers, and bounded authority make work continue across sessions. Multiple agents are optional. Retries need idempotency; a saved checkpoint alone does not prevent duplicate external actions.',checks:[['Restart','Reload state and determine whether an external effect already happened before retrying.'],['Authority','Recheck permissions when acting; old consent may no longer cover the action.'],['Operations','Observe failures, cap cost, and provide a pause switch and a path to a person.']]},
  'human-in-the-loop':{title:'Approval applies to a particular action.',subtitle:'The exact payload, destination, version, and expiry are part of the decision.',nodes:[n('Proposed action','The model drafts a concrete request',0,0,'model'),n('Validate proposal','Schema, allowed scope, current state',1,0,'control'),n('Human review','Show payload and consequences',2,0,'control'),n('Revise or reject','Changed proposal needs fresh review',0,1,'end'),n('Record the outcome','Receipt + idempotency key',1,1),n('Execute once','Recheck approval and current state',2,1)],edges:[e(0,1,'proposal'),e(1,2,'valid request'),e(2,5,'approved'),e(5,4,'receipt','data'),e(2,3,'changes / refusal',undefined,'outside'),e(3,0,'revised proposal','return')],distinction:'A human clicking approve is one control, not a substitute for validation. Approval should become invalid when the reviewed action changes; execution must also handle retries and stale state.',checks:[['Show','What will happen, where, to whom, and whether it can be undone.'],['Bind','Hash or version the exact proposal and scope; set an appropriate expiry.'],['Enforce','Check again at execution, and reconcile ambiguous outcomes before retrying.']]},
};

export function edgeGeometry(a:ArchitectureNode,b:ArchitectureNode,edge:ArchitectureEdge){
  const w=246,h=86;
  if(edge.route==='outside') {
    const y=Math.max(a.y,b.y)+h+38;
    if(a.x===b.x) return {path:`M ${a.x+w} ${a.y+43} H 958 V ${b.y+43} H ${b.x+w+4}`,x:972,y:(a.y+b.y)/2+43,vertical:true};
    return {path:`M ${a.x+w} ${a.y+43} H 958 V ${y} H 8 V ${b.y+43} H ${b.x-4}`,x:(a.x+b.x)/2+123,y:y-9};
  }
  if(a.x===b.x){const down=b.y>a.y;return {path:`M ${a.x+123} ${a.y+(down?h:0)} V ${b.y+(down?-5:h+5)}`,x:a.x+137,y:(a.y+b.y)/2+47};}
  const right=b.x>a.x,x1=a.x+(right?w:0),x2=b.x+(right?-5:w+5),y1=a.y+43,y2=b.y+43;
  return {path:`M ${x1} ${y1} C ${(x1+x2)/2} ${y1}, ${(x1+x2)/2} ${y2}, ${x2} ${y2}`,x:(x1+x2)/2,y:(y1+y2)/2-12};
}
