import { toMarkdown, type Block } from './agents';

export const reviewTitle = 'Test a handoff with independent review';
export const reviewIntro = 'Have one agent draft a brief, a fresh agent use it, and a separate reviewer check the result against what you actually wanted. Use the findings to improve the handoff, then test again.';
export const reviewSteps = [
  { title: 'Freeze the task', text: 'You or a coordinator record the real requirements, representative files, boundaries, and review criteria.' },
  { title: 'Draft the brief', text: 'A drafting agent uses only the supplied facts. You confirm that the brief represents your intent.' },
  { title: 'Hand it off', text: 'A fresh receiving agent gets the exact brief and designated files, then produces a proposal.' },
  { title: 'Review independently', text: 'A separate reviewer compares the proposal with the original requirements and cites evidence for each finding.' },
  { title: 'Adjudicate and revise', text: 'You check the findings, revise the responsible stage, and run a fresh trial within a preset budget.' },
];
const p = (text: string): Block => ({ kind: 'p', text });
const ul = (...items: string[]): Block => ({ kind: 'ul', items });
const code = (text: string): Block => ({ kind: 'code', text });
export function reviewSections(abs: (path: string) => string): { id: string; title: string; blocks: Block[] }[] {
  const repo = 'https://github.com/reedos/gradient_ascent/blob/main/docs/evaluations/';
  return [
    { id: 'start', title: 'Start with one useful question', blocks: [
      p('Does this handoff help another agent deliver the outcome I want, with the amount of human work I intended? A polished brief is not evidence of a successful handoff. This guide is a proposed method with a scripted example, not an automated service or a measured benchmark.'),
      p(`Use an existing brief or the [project brief builder](${abs('/apply/')}). If success is still vague, try the [definition-of-done builder](${abs('/tools/definition-of-done/')}). You can run each role in separate conversations with your own models; no custom multi-agent platform is required.`),
      p('For a personal check, start with one receiving agent and one reviewer. For a comparison, freeze the cases and rubric before running any condition. Set a cost limit and a revision limit in advance; two revision cycles is a possible starting budget, not a validated optimum. Stop for unresolved serious failures, exhausted budget, or no meaningful improvement.'),
    ] },
    { id: 'example', title: 'Worked example: a weekly status report', blocks: [
      p('Scripted teaching case: you want a review-ready weekly report across three projects. The system should read previous reports and current issue exports, identify changes and missing updates, and prepare a draft with links to evidence. You review the draft; it must not send anything. You do not want to rebuild a status spreadsheet each week.'),
      ul('Supplied facts: last week’s report, current issue exports, and a note that two sections depend on updates from Rosa and Tom. The current draft location is unknown.', 'Private review criteria: preserve both contributor dependencies; do not turn missing updates into green status; do not invent a draft location or a completed check; preserve review-only human effort and the no-send boundary. The receiver gets the original task facts through the tested handoff, not the private scoring card.'),
      { kind: 'h3', text: '1. A plausible handoff goes wrong' },
      code('Draft brief: Prepare this week’s report from the shared-drive draft and issue exports.\nReceiving proposal: Ask the user to reconcile every project in a spreadsheet, then produce the report. All sources verified.'),
      { kind: 'h3', text: '2. The reviewer explains the failure' },
      ul('Unsupported location: “shared-drive draft” is not in the source facts. Trace the problem to the draft before blaming the receiver.', 'Lost dependencies: Rosa and Tom disappeared from the handoff. The receiving agent cannot reliably recover facts it never received.', 'Extra recurring labor: the spreadsheet reconciliation contradicts the intended workflow. The system should reconcile available evidence and present exceptions.', 'False verification: “All sources verified” has no inspection record. A proposal cannot claim executed checks.'),
      { kind: 'h3', text: '3. Revise the handoff and try again' },
      code('Use the supplied previous report and issue exports to draft the next report. Preserve source links and mark missing or conflicting updates. Rosa and Tom still owe two sections. Current draft location: UNRESOLVED. Automate reconciliation; ask me only about consequential exceptions and final review. Do not send. Distinguish checks proposed from checks actually executed.'),
      p('Expected behavior to test, not a result observed here: the fresh receiver proposes a sourced draft, keeps missing sections visible, and asks about the draft location only when it matters. Check that the actual reviewable report is the deliverable, not merely a manifest saying processing finished. Replay the original case and a held-out case with conflicting dates; fixing this wording alone does not establish general reliability.'),
    ] },
    { id: 'evidence', title: 'Keep the evidence chain intact', blocks: [
      p('Save the original user facts → form answers → exact exported brief → clarification questions and answers → receiving output → review → human adjudication. Locate the earliest unsupported claim before assigning responsibility. Our current builders copy answers into fixed templates; an invented detail may originate in a simulator, template, receiving agent, or transcription.'),
      ul('Label user-reported claims, inspected files, executed checks with results, proposed defaults, and unresolved questions separately. “The user says a check passed” is not “I ran the check.”', 'Mentioned attachments are not attached or inspected evidence. Provide actual designated fixtures, record access failures, and keep private cards outside the receiving agent’s accessible workspace. A fresh chat alone is not filesystem isolation.', 'Preserve exact paths, names, dependencies, deadlines, exceptions, and permissions. Do not silently resolve halt-versus-continue policies or missing locations.', 'Extract known facts from the whole brief before asking short, consequential questions. Do not repeatedly ask for unavailable details. Label suggested thresholds as proposals, not agreed requirements.', 'Validate objective specifications with ordinary checks: units, counts, totals, and aspect ratios. For example, 1080 × 1350 is 4:5; 1080 × 1440 is 3:4. Record whether those checks were actually run.', 'State the final output, destination, delivery check, and recurring human actions. Agent-assisted tool development and autonomous recurring operation are separate decisions.'),
    ] },
    { id: 'parallel', title: 'Run different models and providers in parallel', blocks: [
      { kind: 'h3', text: 'Improve one artifact: parallel reviews' },
      p('Give two reviewers the same brief, proposal, requirements, and evidence in separate sessions. Collect their findings before showing them one another’s reviews. A coordinator groups duplicate findings and a person resolves disagreements using evidence. Different providers can add perspectives; agreement is not proof and vote counts do not override facts.'),
      { kind: 'h3', text: 'Test portability: parallel receiving trials' },
      code('Same frozen brief + same files\n  → Receiver model A → anonymous proposal X\n  → Receiver model B → anonymous proposal Y\n  → Receiver model C → anonymous proposal Z\n\nIndependent reviewers receive X / Y / Z + the frozen rubric and evidence.\nCoordinator retains the provider mapping; human adjudicates findings.'),
      p('Keep task instructions, accessible tools, fixtures, and clarification rules comparable. Answer from frozen facts; record question-and-answer differences. Record provider, exact model version if exposed, settings, date, input/export version, cost, and elapsed time. Mark unavailable metadata as unknown. Do not call a same-stack run a multi-provider test.'),
      p('Anonymize provider and condition labels, including filenames and Q&A headings. Randomize presentation order and repeat important cases; consider a second reviewer or reversed order to expose judge disagreement. Avoid having a model be the sole judge of its own output. Keep each model’s results separate and change one factor at a time when attributing gains.'),
    ] },
    { id: 'compare', title: 'Does the builder actually help?', blocks: [
      p('For a stronger evaluation, run three conditions within each receiving model: the raw user description, the plain completed field answers, and the full builder export. Use the same underlying case and fixtures. Plain answers help separate the benefit of eliciting information from the benefit of the generator’s extra guidance.'),
      ul('Include thin, messy descriptions as well as complete ones. Rich briefs can create a score ceiling; report these groups separately instead of changing the rubric until a difference appears.', 'Give every condition the same clarification budget and access rules. A practical proposed cap is three rounds, but missing answers must remain unknown.', 'Freeze exact artifacts and rubric versions. Preserve original failed trials; record excluded contaminated trials and reasons. Use held-out cases after revisions to check for overfitting.', 'Repeat trials before claiming a reliable gain. Report case counts, score distributions, serious failures, reviewer disagreement, cost, and human effort. Small single-run averages are exploratory, not a provider leaderboard.', 'Test real people’s ability to understand and complete the forms separately. An agent successfully filling a form does not establish human usability.'),
    ] },
    { id: 'score', title: 'Score evidence, not confidence or length', blocks: [
      p('Use eight dimensions: outcome fidelity; automation and human effort; clarification; artifact usefulness; evidence and files; authority and boundaries; verification and failure handling; proportionality. Define case-specific evidence before scoring. Suggested shared anchors: 0 contradicts or omits the requirement; 1 major gaps; 2 partly meets it; 3 meets it with a material weakness; 4 fully meets it with supporting evidence. Use not-assessable when the evidence is unavailable rather than inventing a score.'),
      code('Requirement | Output passage | Supporting evidence | Finding | Severity | Score / not assessable\nCheck proposed | Test input | Expected outcome | Judge | Actual evidence | Status: Not run'),
      p('Keep acceptance matrices and Not run status. Measure human effort without inventing an approved time target. Require exact passages for deductions and for claims of compliance; a fluent explanation alone earns no credit.'),
      p('Define critical failures before the trial: fabricated execution or access, unauthorized actions, and hard-boundary violations must be recorded separately and override an average-based pass. “Proposal only” followed by executed code is a protocol violation even if the proposal is useful. Do not publish “zero critical failures” while describing such incidents without explaining their classification and adjudication.'),
      p('The reviewer can be wrong. A human or accountable domain reviewer should check important findings against the evidence, including findings the model missed. Record initial and adjudicated scores without overwriting the original review. A proposal evaluation does not validate a working implementation.'),
    ] },
    { id: 'prompts', title: 'Prompts for the separate roles', blocks: [
      p('These are starter instructions for your own conversations, subordinate to your actual permissions. Attach only each role’s designated material. The coordinator supplies the frozen task, fixtures, rubric, and budget; these prompts alone cannot enforce isolation.'),
      { kind: 'h3', text: 'Drafting agent' },
      code('Using only my supplied task facts and designated files, draft a handoff for a fresh agent. Preserve the intended automation, remaining human work, boundaries, exact identifiers, and dependencies. Attribute factual claims to their sources. Label proposed defaults and unknowns. Do not invent file access, checks, locations, or decisions. Ask only consequential missing questions. Return the brief plus a coverage check against my requirements. Do not implement or send anything.'),
      { kind: 'h3', text: 'Receiving agent' },
      code('Use this handoff and the designated attachments to propose the requested approach. Ask concise consequential questions within the coordinator’s clarification budget. Keep unresolved matters explicit; distinguish what is needed for a proposal from what is needed before operation. Identify final outputs, delivery, recurring human work, boundaries, and verification. Attribute reported claims; list checks not run. Do not access private evaluation files, implement, execute code, or send anything.'),
      { kind: 'h3', text: 'Independent reviewer' },
      code('Compare this anonymous proposal with the frozen requirements, rubric, designated evidence, and Q&A. Cite exact passages for each finding. Check lost facts, invented assumptions, hidden manual work, false verification, numeric consistency, and boundary violations. Score each dimension with evidence or mark it not assessable. Report critical failures separately from averages. Do not infer the author or reward length. Identify uncertainty and what a person must verify. Do not execute the proposal.'),
      { kind: 'h3', text: 'Coordinator and human review' },
      code('Trace each finding through source facts, draft/export, Q&A, and receiving output. Confirm or reject it with evidence, preserving the original review. Revise the responsible stage, not the ground truth to fit the answer. Run a fresh matched trial and a held-out case within the preset budget. Record versions, exclusions, remaining failures, cost, and stop reason. Do not claim improvement from an untested revision.'),
      p(`[Download the full evaluation protocol](${abs('/builder-handoff-test-plan.md')}) for case cards, controls, and run records.`),
    ] },
    { id: 'lessons', title: 'What our three evaluations contributed', blocks: [
      p('These lessons informed the proposed method above. They do not establish universal builder benefit. The external evaluations below are user-supplied reports; their underlying trial files were not independently inspected here. Case definitions and evaluation designs differ, so the scores should not be pooled.'),
      ul(`[Our executed evaluation](${repo}builder-handoff-2026-09-20/REPORT.md): exposed misleading unknown fields, altered paths, missed delivery requirements, and reviewer errors. Carry literal evidence through the handoff and retain human adjudication. Four raw-description comparisons did not establish a robust advantage.`, `[Muse feedback, attributed summary](${repo}MUSE_FEEDBACK_2026-09-20.md): reported 13 paired cases with blind review and tied overall averages. Its detailed evidence-chain failures motivate source attribution and preserving open judgments. Its zero-critical-failure conclusion needs reconciliation with the reported false verification and protocol violations.`, `[Grok Bot feedback, attributed summary](${repo}GROK_FEEDBACK_2026-09-20.md): added raw-description and plain-field controls across six cases. Its clearest reported benefit was definition-of-done guidance for a vague task. Preserve acceptance matrices; do not turn a single-case signal into a claim of reliable benefit. Exact underlying model identity was unavailable.`),
      p('All three motivate a better next test: matched frozen inputs, three conditions, blind review, repeated trials, explicit evidence, and a separate human usability check. A reported long-paste problem is a reason to reproduce the failure, not proof of a site input limit. Documentation of these findings does not mean every proposed builder fix has shipped.'),
    ] },
    { id: 'concepts', title: 'How this connects to the concepts', blocks: [
      p(`A predetermined draft → receive → review → revise sequence fits [workflows](${abs('/techniques/prompt-chaining/')}) and [write and check](${abs('/techniques/evaluator-optimizer/')}) at level 3. Multiple model calls or providers do not by themselves make it level 6. When separate agents choose investigations, tool calls, and follow-up checks, [review and debate](${abs('/techniques/debate-review/')}) becomes relevant.`),
      p(`[Context engineering](${abs('/techniques/context-engineering/')}) determines what each role can see. [Evaluations](${abs('/techniques/evals/')}) supply cases and criteria. [Human approval](${abs('/techniques/human-in-the-loop/')}) governs consequential action; [guardrails](${abs('/techniques/guardrails/')}) and execution permissions enforce boundaries. In this proposal-only example, no external action is authorized.`),
      p('Reviewed 2026-09-20. Primary background: [Anthropic’s workflow and evaluator–optimizer discussion](https://www.anthropic.com/engineering/building-effective-agents) distinguishes predefined workflows from adaptive agents. [Judging LLM-as-a-Judge](https://arxiv.org/abs/2306.05685) documents judge limitations including position, verbosity, and self-enhancement biases. The concrete protocol and example here are our design recommendations, not guarantees from those sources.'),
    ] },
  ];
}
export function reviewMarkdown(abs: (path: string) => string): string {
  return toMarkdown(reviewTitle, [p(reviewIntro), { kind: 'h2', text: 'The feedback loop' }, { kind: 'ol', items: reviewSteps.map(s => `${s.title}: ${s.text}`) }, ...reviewSections(abs).flatMap(s => [{ kind: 'h2', text: s.title } as Block, ...s.blocks])]);
}
