// Editorial labels and explanations for the selected timeline milestones.
export const selections: Record<number, { id?: string; title: string; event: string; note: string }> = {
  1: { title: 'ChatGPT', event: 'Research preview released', note: 'A recognizable public example of prompting a language model. Earlier products existed; this is a selected milestone, not the invention of prompting.' },
  2: { title: 'Perplexity', event: 'Search-and-answer product launched', note: 'The early Perplexity Ask combined retrieved search results with a generated answer and citations. That is the specific Level 2 pattern illustrated here, not a classification of every later Perplexity feature. Cofounder Aravind Srinivas dates the launch to December 7, 2022 in a retrospective interview; this is founder testimony, not a contemporaneous launch announcement.' },
  3: { id: 'zapier-openai-2022', title: 'OpenAI steps in Zapier', event: 'Archived availability evidence', note: 'A model call inside a workflow whose steps are set in advance. December 9 is an archived-page capture, not a confirmed launch date. Microsoft 365 Copilot remains a related workplace-AI milestone, rather than the defining workflow example.' },
  4: { title: 'ChatGPT plugins', event: 'Limited alpha announced · waitlist', note: 'A visible example of a model choosing a tool. This dates the limited rollout, not broad availability or the first implementation of tool use.' },
  5: { title: 'Operator', event: 'Browser-use agent preview · US Pro', note: 'The agent observes a browser, acts, and decides what to do next. This is a browser-use milestone; agents and autonomous loops existed earlier.' },
  6: { id: 'anthropic-multiagent-research-2025', title: 'Claude Research', event: 'Multi-agent architecture documented', note: 'Anthropic explicitly describes a lead agent delegating to parallel subagents on June 13. Research launched on April 15, but that announcement does not establish whether the same architecture was in use then. June is the documentation date, not an asserted deployment date.' },
  7: { title: 'Grok Bot', event: 'Paid beta released', note: 'An example of agents that keep working beyond an interactive session. The product also describes a team of agents: one product can illustrate more than one level.' },
};
